# Uncomment this line to define a global platform for your project

platform :ios, '6.0'

target 'AWBTCChinaAPI' do

# Networking
pod 'AFJSONRPCClient', '~> 2.1.1'

end

# target 'AWBTCChinaAPITests' do

# end

