# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AWBTCChinaAPIDemo' do

# Networking
pod 'AFJSONRPCClient', '~> 2.1.1'

end

target 'AWBTCChinaAPIDemoTests' do

end

